CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	email VARCHAR(254) NOT NULL UNIQUE,
	CONSTRAINT user_name_not_blank CHECK (TRIM(name) <> ''),
	CONSTRAINT email_not_blank CHECK (TRIM(email) <> ''),
	CONSTRAINT email_no_whitespace CHECK (email NOT LIKE '% %')
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	CONSTRAINT category_name_not_blank CHECK (TRIM(name) <> '')
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    initiator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    -- location
    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,
    request_moderation BOOL NOT NULL,
    state VARCHAR(9) NOT NULL,
    paid BOOL NOT NULL,
    title VARCHAR(120) NOT NULL,
    -- constraints
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    event_id BIGINT REFERENCES events(id) ON DELETE SET NULL,
    requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR NOT NULL,
    -- constraints
);

CREATE TABLE IF NOT EXISTS compilation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOL NOT NULL,
    title VARCHAR(50) NOT NULL,
    -- constraints
);